import Config

# Configure your database
config :second_brain, SecondBrain.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "second_brain_dev",
  port: 5432,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :second_brain, SecondBrainWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "O/5Bui51zyiNxJmuZUGt775X9+AsHKkotPmrLRPk1dMZuGTLtBe95tDskG/dOIAr",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :second_brain, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

#####

config :ex_aws,
  access_key_id: "minio",
  secret_access_key: "minio123",
  region: "us-east-1",
  s3: [
    scheme: "http://",
    host: "localhost",
    port: 9000
  ]

config :second_brain, SecondBrain.BrainDiskS3,
  bucket_name: "second-brain-dev",
  max_sessions_per_file: 4

config :second_brain, SecondBrainWeb.Frontend, url: "http://localhost:3000"
